name: vuitton_club
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  font_awesome_flutter: ^9.2.0
  flutter_launcher_icons: ^0.9.2
  connectivity: ^3.0.6

  firebase: ^9.0.2
  cloud_firestore: ^2.5.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  http: ^0.13.3
  country_code_picker: ^2.0.2
  country_picker: ^2.0.9
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  device_info: ^2.0.3
  dart_ipify: ^1.1.1
  flutter_insta: ^1.0.0
  insta_public_api: ^0.1.2
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Bizmo
      fonts:
        - asset: fonts/Bizmo Black.ttf
    - family: Bizmo2
      fonts:
        - asset: fonts/Bizmo Medium.ttf
